export const allStars = {
    "Joel Embiid": {
        "Finishing": "A+",
        "Mid-Range": "A+",
        "3PT": "B-",
        "Playmaking": "C",
        "Rebounding": "A-",
        "Defense": "A+",
        "OVR": 96,
        "ID": 203954,
        "Team": "Philadelphia 76ers",
        "Primary Position": "C",
        "Secondary Position": "PF",
    },
    "Ja Morant": {
        "Finishing": "S",
        "Mid-Range": "A-",
        "3PT": "B",
        "Playmaking": "A+",
        "Rebounding": "B",
        "Defense": "B",
        "OVR": 94,
        "ID": 1629630,
        "Team": "Memphis Grizzlies",
        "Primary Position": "PG",
        "Secondary Position": "SG",
    },
    "Jayson Tatum": {
        "Finishing": "A+",
        "Mid-Range": "A",
        "3PT": "A+",
        "Playmaking": "A-",
        "Rebounding": "B+",
        "Defense": "A+",
        "OVR": 95,
        "ID": 1628369,
        "Team": "Boston Celtics",
        "Primary Position": "SF",
        "Secondary Position": "PF",
    },
    "Andrew Wiggins": {
        "Finishing": "A",
        "Mid-Range": "A",
        "3PT": "A-",
        "Playmaking": "B",
        "Rebounding": "C+",
        "Defense": "A",
        "OVR": 84,
        "ID": 203952,
        "Team": "Golden State Warriors",
        "Primary Position": "SF",
        "Secondary Position": "PF",
    },
    "Trae Young": {
        "Finishing": "A-",
        "Mid-Range": "A",
        "3PT": "A+",
        "Playmaking": "S",
        "Rebounding": "F",
        "Defense": "D+",
        "OVR": 90,
        "ID": 1629027,
        "Team": "Atlanta Hawks",
        "Primary Position": "PG",
        "Secondary Position": "SG",
    },
    "Giannis Antetokounmpo": {
        "Finishing": "S",
        "Mid-Range": "C-",
        "3PT": "D+",
        "Playmaking": "A+",
        "Rebounding": "A",
        "Defense": "A+",
        "OVR": 97,
        "ID": 203507,
        "Team": "Milwaukee Bucks",
        "Primary Position": "PF",
        "Secondary Position": "SF",
    },
    "Stephen Curry": {
        "Finishing": "A+",
        "Mid-Range": "A+",
        "3PT": "S",
        "Playmaking": "A+",
        "Rebounding": "C+",
        "Defense": "B+",
        "OVR": 97,
        "ID": 201939,
        "Team": "Golden State Warriors",
        "Primary Position": "PG",
        "Secondary Position": "SG",
    },
    "DeMar DeRozan": {
        "Finishing": "A+",
        "Mid-Range": "S",
        "3PT": "C-",
        "Playmaking": "B+",
        "Rebounding": "D+",
        "Defense": "B+",
        "OVR": 88,
        "ID": 201942,
        "Team": "Chicago Bulls",
        "Primary Position": "SG",
        "Secondary Position": "SF",
    },
    "Kevin Durant": {
        "Finishing": "A+",
        "Mid-Range": "S",
        "3PT": "A+",
        "Playmaking": "A",
        "Rebounding": "B-",
        "Defense": "A",
        "OVR": 96,
        "ID": 201142,
        "Team": "Brooklyn Nets",
        "Primary Position": "SF",
        "Secondary Position": "PF",
    },
    "Nikola Jokic": {
        "Finishing": "A+",
        "Mid-Range": "A+",
        "3PT": "B",
        "Playmaking": "S",
        "Rebounding": "A",
        "Defense": "B+",
        "OVR": 96,
        "ID": 203999,
        "Team": "Denver Nuggets",
        "Primary Position": "C",
        "Secondary Position": "PF",
    },
    "LaMelo Ball": {
        "Finishing": "A-",
        "Mid-Range": "B-",
        "3PT": "A-",
        "Playmaking": "A+",
        "Rebounding": "B-",
        "Defense": "B+",
        "OVR": 87,
        "ID": 1630163,
        "Team": "Charlotte Hornets",
        "Primary Position": "PG",
        "Secondary Position": "SG",
    },
    "Darius Garland": {
        "Finishing": "A",
        "Mid-Range": "A-",
        "3PT": "A",
        "Playmaking": "A+",
        "Rebounding": "F",
        "Defense": "B",
        "OVR": 87,
        "ID": 1629636,
        "Team": "Cleveland Cavaliers",
        "Primary Position": "PG",
        "Secondary Position": "SG",
    },
    "James Harden": {
        "Finishing": "B+",
        "Mid-Range": "A",
        "3PT": "A-",
        "Playmaking": "A+",
        "Rebounding": "C+",
        "Defense": "B",
        "OVR": 89,
        "ID": 201935,
        "Team": "Philadelphia 76ers",
        "Primary Position": "SG",
        "Secondary Position": "PG",
    },
    "Zach LaVine": {
        "Finishing": "A",
        "Mid-Range": "A-",
        "3PT": "A",
        "Playmaking": "A",
        "Rebounding": "C+",
        "Defense": "B",
        "OVR": 87,
        "ID": 203897,
        "Team": "Chicago Bulls",
        "Primary Position": "SG",
        "Secondary Position": "SF",
    },
    "Fred VanVleet": {
        "Finishing": "B+",
        "Mid-Range": "B",
        "3PT": "A",
        "Playmaking": "A",
        "Rebounding": "D",
        "Defense": "A",
        "OVR": 84,
        "ID": 1627832,
        "Team": "Toronto Raptors",
        "Primary Position": "PG",
        "Secondary Position": "SG",
    },
    "Jimmy Butler": {
        "Finishing": "A",
        "Mid-Range": "B",
        "3PT": "B-",
        "Playmaking": "A",
        "Rebounding": "B-",
        "Defense": "A+",
        "OVR": 93,
        "ID": 202710,
        "Team": "Miami Heat",
        "Primary Position": "SF",
        "Secondary Position": "SG",
    },
    "Khris Middleton": {
        "Finishing": "B+",
        "Mid-Range": "A-",
        "3PT": "B+",
        "Playmaking": "B+",
        "Rebounding": "C",
        "Defense": "A",
        "OVR": 86,
        "ID": 203114,
        "Team": "Milwaukee Bucks",
        "Primary Position": "SF",
        "Secondary Position": "SG",
    },
    "Jarrett Allen": {
        "Finishing": "A-",
        "Mid-Range": "B",
        "3PT": "D-",
        "Playmaking": "F",
        "Rebounding": "A+",
        "Defense": "A",
        "OVR": 84,
        "ID": 1628386,
        "Team": "Cleveland Cavaliers",
        "Primary Position": "C",
        "Secondary Position": "PF",
    },
    "Devin Booker": {
        "Finishing": "A",
        "Mid-Range": "A",
        "3PT": "A+",
        "Playmaking": "A+",
        "Rebounding": "C+",
        "Defense": "B+",
        "OVR": 91,
        "ID": 1626164,
        "Team": "Phoenix Suns",
        "Primary Position": "SG",
        "Secondary Position": "PG",
    },
    "Luka Doncic": {
        "Finishing": "A+",
        "Mid-Range": "A+",
        "3PT": "A+",
        "Playmaking": "S",
        "Rebounding": "A",
        "Defense": "B+",
        "OVR": 96,
        "ID": 1629029,
        "Team": "Dallas Mavericks",
        "Primary Position": "PG",
        "Secondary Position": "SG",
    },
    "Donovan Mitchell": {
        "Finishing": "A+",
        "Mid-Range": "A",
        "3PT": "A+",
        "Playmaking": "A+",
        "Rebounding": "D+",
        "Defense": "B+",
        "OVR": 91,
        "ID": 1628378,
        "Team": "Cleveland Cavaliers",
        "Primary Position": "SG",
        "Secondary Position": "PG",
    },
    "Dejounte Murray": {
        "Finishing": "A-",
        "Mid-Range": "A+",
        "3PT": "C+",
        "Playmaking": "A+",
        "Rebounding": "C+",
        "Defense": "A+",
        "OVR": 86,
        "ID": 1627749,
        "Team": "Atlanta Hawks",
        "Primary Position": "PG",
        "Secondary Position": "SG",
    },
    "Chris Paul": {
        "Finishing": "A",
        "Mid-Range": "S",
        "3PT": "B",
        "Playmaking": "S",
        "Rebounding": "C-",
        "Defense": "A+",
        "OVR": 89,
        "ID": 101108,
        "Team": "Phoenix Suns",
        "Primary Position": "PG",
        "Secondary Position": "SG",
    },
    "Draymond Green": {
        "Finishing": "B-",
        "Mid-Range": "D-",
        "3PT": "C-",
        "Playmaking": "A",
        "Rebounding": "B-",
        "Defense": "A+",
        "OVR": 83,
        "ID": 203110,
        "Team": "Golden State Warriors",
        "Primary Position": "PF",
        "Secondary Position": "C",
    },
    "Rudy Gobert": {
        "Finishing": "B+",
        "Mid-Range": "D-",
        "3PT": "F",
        "Playmaking": "D",
        "Rebounding": "A+",
        "Defense": "A+",
        "OVR": 86,
        "ID": 203497,
        "Team": "Minnesota Timberwolves",
        "Primary Position": "C",
        "Secondary Position": "PF",
    },
    "Karl-Anthony Towns": {
        "Finishing": "A",
        "Mid-Range": "A",
        "3PT": "B+",
        "Playmaking": "B-",
        "Rebounding": "B+",
        "Defense": "B",
        "OVR": 87,
        "ID": 1626157,
        "Team": "Minnesota Timberwolves",
        "Primary Position": "C",
        "Secondary Position": "PF",
    },
}

export const teams = [
    "Atlanta Hawks",
    "Boston Celtics",
    "Brooklyn Nets",
    "Charlotte Hornets",
    "Chicago Bulls",
    "Cleveland Cavaliers",
    "Dallas Mavericks",
    "Denver Nuggets",
    "Detroit Pistons",
    "Golden State Warriors",
    "Houston Rockets",
    "Indiana Pacers",
    "Los Angeles Clippers",
    "Los Angeles Lakers",
    "Memphis Grizzlies",
    "Miami Heat",
    "Milwaukee Bucks",
    "Minnesota Timberwolves",
    "New Orleans Pelicans",
    "New York Knicks",
    "Oklahoma City Thunder",
    "Orlando Magic",
    "Philadelphia 76ers",
    "Phoenix Suns",
    "Portland Trail Blazers",
    "Sacramento Kings",
    "San Antonio Spurs",
    "Toronto Raptors",
    "Utah Jazz",
    "Washington Wizards",
]

export const teamsToAbb = {
    "Atlanta Hawks": "atl",
    "Boston Celtics": "bkn",
    "Brooklyn Nets": "bos",
    "Charlotte Hornets": "cha",
    "Chicago Bulls": "chi",
    "Cleveland Cavaliers": "cle",
    "Dallas Mavericks": "dal",
    "Denver Nuggets": "den",
    "Detroit Pistons": "det",
    "Golden State Warriors": "gsw",
    "Houston Rockets": "hou",
    "Indiana Pacers": "ind",
    "Los Angeles Clippers": "lac",
    "Los Angeles Lakers": "lal",
    "Memphis Grizzlies": "mem",
    "Miami Heat": "mia",
    "Milwaukee Bucks": "mil",
    "Minnesota Timberwolves": "min",
    "New Orleans Pelicans": "nop",
    "New York Knicks": "nyk",
    "Oklahoma City Thunder": "okc",
    "Orlando Magic": "orl",
    "Philadelphia 76ers": "phi",
    "Phoenix Suns": "phx",
    "Portland Trail Blazers": "por",
    "Sacramento Kings": "sac",
    "San Antonio Spurs": "sas",
    "Toronto Raptors": "tor",
    "Utah Jazz": "uta",
    "Washington Wizards": "was",
}

export const positions = [
    "PG",
    "SG",
    "SF",
    "PF",
    "C"
]

export const stats = [
    "Finishing",
    "Mid-Range",
    "3PT",
    "Playmaking",
    "Rebounding",
    "Defense",
]

export const sortByStats = [
    "Alphabetical",
    "OVR"
].concat(stats)